name: CI

on:
#  pull_request:
#    types: [ opened, synchronize, reopened ]
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Compile
        run: mvn --batch-mode compile

      - name: Get project_version
        id: project_version
        run: echo "::set-output version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Publish Snapshot
        if: endsWith( steps.project_version.version, '-SNAPSHOT' ) && github.ref == 'refs/heads/test' # TODO change test to master
        # See https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven
        run: mvn --batch-mode deploy -DaltReleaseDeploymentRepository=https://maven.pkg.github.com/${{github.repository}}-snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
