name: CI

on:
#  pull_request:
#    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Downloading all the dependencies is very log spammy so we do this in its own step
      - name: Download Maven Dependencies
        run: mvn --batch-mode dependency:go-offline

      - name: Compile
        run: mvn --batch-mode compile

      - name: Package
        run: mvn --batch-mode package
