name: font-sprite

on:
  push:
  workflow_dispatch:

jobs:
  font-sprite:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [macos-11, macos-10.15, ubuntu-18.04, ubuntu-20.04, windows-2016, windows-2019, windows-2022]
#        java_version: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
        os: [macos-11, ubuntu-20.04]
        java_version: [8, 17]
    steps:
      - name: Configure maven
        id: maven
        if: ${{ matrix.java }} != 8
        run: echo "::set-output name=opts::--add-exports java.desktop/sun.java2d.pipe=ALL-UNNAMED"

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: temurin
          cache: maven

      # Downloading all the dependencies is very log spammy, so we do this in its own step.
      - name: Prime maven cache
        run: mvn --batch-mode dependency:go-offline

      - name: Test
        env:
          MAVEN_OPTS: ${{ steps.maven.outputs.opts }}
        run: |
          mvn --batch-mode compile compiler:testCompile exec:java \
             -Dexec.mainClass=org.junit.platform.console.ConsoleLauncher \
             -Dexec.classpathScope=test \
             -Dexec.args="--disable-ansi-colors --select-class net.sourceforge.plantuml.ugraphic.FontSpriteExperiments --select-class net.sourceforge.plantuml.ugraphic.RenderingEngineTest"

      - name: Upload test outputs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_number }}-${{ matrix.os }}-java${{ matrix.java_version }}-images-created
          path: target/images-created/*
