name: License MIT

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build_license_mit:
    name: 'Build License MIT'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set MIT version 
        run: sed -i "s/version = .*/version = mit-${{ inputs.release-version }}/" gradle.properties

      - name: Run pre-processor
        run: |
          java -jar sjpp.jar
          java -jar sjpp.jar src src-mit __MIT__

      - name: Rename build-mit.gradle
        run: |
          cp build-mit.gradle.kts build.gradle.kts
 
      - name: Compile (jar, sourcesJar)
        run: gradle jar sourcesJar --no-daemon --console verbose

      - name: Print version
        run: |
          java -jar build/libs/plantuml-mit-${{ inputs.release-version }}.jar -version

      - name: Cache License MIT
        uses: actions/cache/save@v3
        with:
          path: "build/libs/plantuml-mit-*"
          key: "license-mit-${{ github.run_id }}"
          enableCrossOsArchive: true
